feat: updating bootstrap
make it a bit more manual by making the user install brew
and cloning the repo themselves.

diff --git a/dotfiles/.local/bin/ds b/dotfiles/.local/bin/ds
--- a/dotfiles/.local/bin/ds
+++ b/dotfiles/.local/bin/ds
@@ -4,6 +4,11 @@
 
 set -e
 
+if ! [[ -x "$(command -v brew)" ]]; then
+  printf "Homebrew (https://brew.sh) is not found but is required.\n"
+    exit 1
+fi
+
 if [[ "$#" == 0 ]]; then
   printf "$(basename "$0"): No flags provided. "
   printf "Please review usage via '$(basename "$0") -h'.\n"
